// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


self.onmessage = (function (e) {
    console.log("I am the Web Worker and I have received a message:");
    console.log(e[""]);
    postMessage("my result");
  });

/*  Not a pure module */
