// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");

Jest.describe("create_webworkers", (function (param) {
        Jest.test("to work", (function (param) {
                var worker = new Worker("script.js");
                return Jest.ExpectJs.toEqual(Jest.ExpectJs.expect(worker.url), "script.js");
              }));
      }));

/*  Not a pure module */
